### ISSUE TITLE
Manager firmware unavailable

### ISSUE THREAD

**Issue by diegoalarc** [pop-os/system76-firmware#100]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

Probably is my laptop to new (Asus zephyrus g15 2022) but I can't find any firmware available.

Laptop description:
> Getting SMBIOS data from sysfs.
> SMBIOS 3.4.0 present.
> 
> Handle 0x0001, DMI type 1, 27 bytes
> System Information
> 	Manufacturer: ASUSTeK COMPUTER INC.
> 	Product Name: ROG Zephyrus G15 GA503RS_GA503RS
> 	Version: 1.0
> 	Serial Number: N9NRCX03D14836F
> 	UUID: 657ed70e-86f6-8d42-92f3-54031d3bc4c5
> 	Wake-up Type: Power Switch
> 	SKU Number:  
> 	Family: ROG Zephyrus G15

**Steps to reproduce (if you know):**

![Screenshot from 2022-11-01 00-42-20](https://user-images.githubusercontent.com/57131432/199129793-4cdd462c-6d40-4a2a-a272-c01b84552a4d.png)

**Expected behavior:**
That some firmware appears (hopefully).

**Other Notes:**
A separate question, do you have an option to update the kernel or is it all cli?

**Comment by mmstick** [comment]
system76-firmware is only used by System76 hardware.
Firmware Manager shows firmware available from system76-firmware or fwupd.
Fwupd gets its firmware metadata from LVFS, and LVFS only has firmware if the vendor uploaded it.
