### ISSUE TITLE
system76-firmware fails to schedule/install on Dell XPS 13 running Pop_OS 22.04 LTS

### ISSUE THREAD

**Issue by jeremyakers** [pop-os/system76-firmware#126]
**Distribution (run `cat /etc/os-release`):**
```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
$ apt policy system76-firmware
system76-firmware:
  Installed: 1.0.55~1699483593~22.04~cb768e7
  Candidate: 1.0.55~1699483593~22.04~cb768e7
  Version table:
 *** 1.0.55~1699483593~22.04~cb768e7 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description:**

For several weeks I have been getting prompted to install new firmware on my laptop (A Dell XPS 13 9300). When I click "Reboot and Install" I get this error:
![Screenshot from 2023-11-18 08-51-50](https://github.com/pop-os/system76-firmware/assets/13689422/4b543f45-f9f3-4c6f-b768-d08527090bc2)

So I did some googling, and found the command line steps here: https://support.system76.com/articles/system-firmware/

So I followed the steps described here, and it also fails, but with a different error:

```
$ sudo system76-firmware-cli schedule
[sudo] password for jeremy: 
Automatic transition: none -> none
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading _140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading _140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading _140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe.tar.xz
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading _140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe.tar.xz
system76-firmware: failed to download: _140bedbf9c3f6d56a9846d2ba7088798683f4da0c248231336e6a05679e4fdfe.tar.xz not found
```

I saw nothing on the system76 website instructions that offered any help for this particular type of error.

**Steps to reproduce (if you know):**
Click "Reboot and Install" or run "sudo system76-firmware-cli schedule"

**Expected behavior:**
Laptop should reboot and firmware should be updated in the process.

**Comment by leviport** [comment]
system76-firmware is specific to System76 machines. The firmware tab in Settings also shows firmware updates that are managed by fwupd/LVFS, which is probably what you're seeing there. I don't know why it's failing for you, but debugging with `fwupdmgr` from CLI will probably be a better place to start than `system76-firmware-cli`.

**Comment by crawfxrd** [comment]
> ...Blocked executable in the ESP...
> [cksum] is present in the dbx

It's failing because a signature was found in the revocation list.

Not exactly sure which binary it is though.
Is our fwupd-efi package up-to-date?

**Comment by Yummy-Yums** [comment]
@jeremyakers @crawfxrd  hello guys, were you able to fix this issue, run into the same issue

**Comment by Yummy-Yums** [comment]
i use a lenovo flex 5 14are

**Comment by leviport** [comment]
This is a fwupdmgr issue, not a system76-firmware issue. As such, I am closing this issue.

**Comment by fxfactorial** [comment]
Also running into this and on a system76 machine thelio

**Comment by leviport** [comment]
@fxfactorial Open a new issue. This one is not related to what you're seeing.
