### ISSUE TITLE
`cargo` crashes with "network failure" while attempting to fetch `ecflash`

### ISSUE THREAD

**Issue by jtherrmann** [pop-os/system76-firmware#131]
**Distribution (run `cat /etc/os-release`):**

Debian GNU/Linux 12 (bookworm)

**Issue/Bug Description:**

Build always fails because `cargo` crashes with a network error.

**Steps to reproduce (if you know):**

Install `cargo` with `sudo apt install cargo`.

Clone https://github.com/pop-os/system76-firmware and `cd` into the repo.

Run `make`. After downloading about 10%, fails with the following error:

```
cargo build --release
    Updating crates.io index
error: failed to get `ecflash` as a dependency of package `system76-firmware v1.0.58 (/home/jth/apps/system76-firmware)`

Caused by:
  failed to load source for dependency `ecflash`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: 0xffff8780 - SSL - The peer notified us that the connection is going to be closed; class=Ssl (16)
make: *** [Makefile:66: target/release/system76-firmware-cli] Error 101
```

**Other Notes:**

I'm attempting to build `system76-firmware` on Debian 12 for use with my Lemur Pro laptop.

I do not use a network proxy. My internet isn't very fast, but works fine for all other use cases (web browsing, video conferencing, installing packages with `apt` and `flatpak`, pushing and pulling with `git`, etc.). Is `cargo` extremely sensitive to momentary network interrupts?

**Comment by MrPenguin07** [comment]
Cannot reproduce here, fresh clone of repo pulls ecflash and make runs without issue;

![image](https://github.com/pop-os/system76-firmware/assets/127086564/a112e15e-25b2-48e4-93c0-ef4b0857fab0)

**Comment by crawfxrd** [comment]
This is not a system76-firmware issue and there is nothing we can do about it.

**Comment by jtherrmann** [comment]
I apologize, you are correct. Building in a Debian 12 EC2 instance worked fine. I guess my local internet connection is too unstable for `cargo`.
