### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by electrickite** [pop-os/system76-firmware#3]
Will this project provide Github releases similar to system76-driver? If releases aren't planned, will commits be tagged with version numbers?

**Comment by jackpot51** [comment]
Are you looking to package this for another distro?

I think we can do tags

**Comment by electrickite** [comment]
@jackpot51 Yes, specifically for Arch, but I’m sure release tagging would help other potential packagers as well. Previously, I was just packaging system76-driver, which has releases, but it has started depending on this package and system76-DKMS.

**Comment by jackpot51** [comment]
I tagged the 1.0.2 release
