### ISSUE TITLE
Two packages install /usr/bin/system76-firmware

### ISSUE THREAD

**Issue by electrickite** [pop-os/system76-firmware#6]
**Distribution (run `cat /etc/os-release`):**
    NAME="Arch Linux"
    PRETTY_NAME="Arch Linux"
    ID=arch
    ID_LIKE=archlinux
    ANSI_COLOR="0;36"
    HOME_URL="https://www.archlinux.org/"
    SUPPORT_URL="https://bbs.archlinux.org/"
    BUG_REPORT_URL="https://bugs.archlinux.org/"

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
system76-firmware 1.0.2
system76-driver 18.04.25

**Issue/Bug Description:**
Both system76-firmware and system76-driver install an executable to `/usr/bin/system76-firmware`

**Steps to reproduce (if you know):**
Install both packages.

**Other Notes:**
Are these two packages incompatible? If not, which system76-firmware executable is the "correct" version?

**Comment by jackpot51** [comment]
@mmstick can you take a look at this? I believe this package should change it's installed binary to something like `system76-firmware-cli` to avoid conflicting with the driver
