### ISSUE TITLE
tail cache sometimes hides updates

### ISSUE THREAD

**Issue by jackpot51** [pop-os/system76-firmware#66]
Sometimes the tail cache is not invalidated and updates do not appear in a timely manner. Removing the tail with `sudo rm /var/cache/system76-firmware-daemon/tail` and restarting the daemon causes updates to appear again.

**Comment by jacobgkau** [comment]
I've isolated a lab machine that's experiencing this issue so we can use it to test a fix when it's available. Let us know if any other info from an affected machine is needed.

**Comment by crawfxrd** [comment]
Can you provide the status of the service along with the `tail` file itself.

```
sudo systemctl status system76-firmware-daemon.service
```

**Comment by jacobgkau** [comment]
These are from an addw2:
[status.txt](https://github.com/pop-os/system76-firmware/files/7123684/status.txt)
[tail.txt](https://github.com/pop-os/system76-firmware/files/7123685/tail.txt)

`ls -alh` shows the `tail` file was last modified July 19th.

**Comment by crawfxrd** [comment]
Issue can be reproduced by replacing the tail file with the one @jacobgkau provided.

After #57 it's never invalidated by timestamp anymore, so it's never going to download a new one.

```
sudo cp ~/tail.txt /var/cache/system76-firmware-daemon/
sudo touch -m --date="2021-01-01" /var/cache/system76-firmware-daemon/tail
```
