### ISSUE TITLE
system76-power daemon is taking too much cpu

### ISSUE THREAD

**Issue by edap** [pop-os/system76-firmware#68]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

System 76 power daemon

**Issue/Bug Description:**

Taking 100% cpu

**Steps to reproduce (if you know):**

I do not know. But one processor is always using 100% of the resources, sometime the fan is way too loud, but I do not know if it is related to this issue.

**Expected behavior:**

When just the browser is running (without videos webGL applications), the daemon should not take that amount of cpu and the fan should be quiet.
![power-daemon](https://user-images.githubusercontent.com/161152/132541922-c1ede1f7-58a3-446e-9ada-b547cdf2c141.png)

**Other Notes:**

**Comment by jacobgkau** [comment]
Is there a reason this was filed in the system76-firmware repository instead of the [system76-power](https://github.com/pop-os/system76-power) repository?

**Comment by edap** [comment]
I have reported the issue on the correct repository https://github.com/pop-os/system76-power/issues/277, thanks @jacobgkau  for the suggestion ;)
