### ISSUE TITLE
meer6 shows a Lenovo ME update

### ISSUE THREAD

**Issue by leviport** [pop-os/system76-firmware#89]
**Distribution (run `cat /etc/os-release`):**
 Pop!\_OS 22.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
$ apt policy fwupd
fwupd:
  Installed: 1.8.0-1pop0~1651249442~22.04~70f32d3
  Candidate: 1.8.0-1pop0~1651249442~22.04~70f32d3
  Version table:
 *** 1.8.0-1pop0~1651249442~22.04~70f32d3 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1.7.5-3 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```
```
$ apt policy system76-firmware
system76-firmware:
  Installed: 1.0.39~1654116394~22.04~f71ce23
  Candidate: 1.0.39~1654116394~22.04~f71ce23
  Version table:
 *** 1.0.39~1654116394~22.04~f71ce23 1002
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
![PXL_20220610_224746319](https://user-images.githubusercontent.com/13512097/173160427-37e03fa4-a210-4d5b-af79-843eddeb5ddd.jpg)

Trying to install this firmware reboots the machine, but nothing ever installs, and and I'm prompted to install this update again after login.

**Steps to reproduce (if you know):**
Open firmware manager on meer6

**Expected behavior:**
Only show installable firmware updates

**Other Notes:**
I also saw a Mattermost user with a Tuxedo laptop report the same thing: https://chat.pop-os.org/pop-os/pl/8nr99qb5eifh7kxamjafgg5puy

**Comment by cwsystem76** [comment]
Opened up an issue with `fwupd` per Jeremy's instructions: https://github.com/fwupd/fwupd/issues/4741

**Comment by cwsystem76** [comment]
`fwupd` folks discovered this last week and fixed it: https://github.com/fwupd/fwupd/issues/4733

The following commands should resolve the issue for a customer as the fix was pushed server-side:

```
fwupdmgr refresh --force
fwupdmgr get-updates
```

I'm asking a System76 customer to test these commands, and have also notified the Tuxedo+Pop!OS user on the Mattermost.

**Comment by leviport** [comment]
Closing since this is resolved
